# Generated by Django 5.0.4 on 2024-04-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_remove_customer_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
